// <auto-generated />
namespace EF_CodeFirst_FaturaTakip_Projesi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FaturaMaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FaturaMaster));
        
        string IMigrationMetadata.Id
        {
            get { return "201903211655254_FaturaMaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
